yosupo06/library-checker-frontend

main.go

use port env

---

templates/navbar.html

Fix a name

---

main.go
templates/submitlist.html

Fixes https://github.com/yosupo06/library-checker-frontend/issues/24.

Conditionally include problem and status in links to other pages

---

templates/submitinfo.html

提出コードにハイライトされていないものがあったので追加しておきました！

add langs for highlight.js

---

templates/submitlist.html

Resolve #44 
URLのパラメータをつくる部分が長いので改行できたら見やすいかなと思ったんですが、どうすればよいか分からなかったのでとりあえず足しておきました…

fix URL parameter with time and id

---

go.sum
main.go
templates/submitlist.html

Resolve #47 
https://github.com/yosupo06/library-checker-judge/pull/127 が終わったらマージお願いします！

add language filter

---

package-lock.json
package.json

upgrade version of katex

---

src/components/SubmissionTable.tsx

add problem url for submissionlist

---

app.yaml

add secure: always

---

.github/workflows/ci.yml
package-lock.json

npm ci を使うと package-lock.json の中身がちょうど使われるので、そのようにしてほしい。node.js のパッケージのバージョン調整で苦しんだときに助かります。ちなみに現状の package-lock.json だと TypeScript のビルドがうまくいきませんでした

use npm ci

---

src/components/NavBar/index.tsx

気づいたので https://github.com/yosupo06/library-checker-frontend/issues/84

fix navbar title

---

package-lock.json
package.json

Reverts yosupo06/library-checker-frontend#110

Revert "update grpc"

---

src/components/NavBar/index.tsx
src/pages/ProblemInfo.tsx

#133 にてprettierが適用ができていなかったため適用しました。
申し訳ないです。

prettierの適用

---

src/components/NavBar/index.tsx
src/components/SourceEditor.tsx

NavBar のコードにて elements:ReactElement[] に随時 push していたものを一つの JSX にまとめました
動作の変更はないです。

Refactoring navbar

---

src/api/client_wrapper.ts
src/components/ProblemList.tsx
src/pages/Problems.tsx

fix #183 
and refactor `Problems.tsx`

fix ac list

---

src/utils/problem.info.test.ts
src/utils/problem.info.ts

fix params handling

---

src/pages/ProblemInfo.tsx

Fix #180
試しに Statement の下にボタンで置いてみました。

Add forum button

---

package-lock.json
package.json
src/utils/statement.parser.test.ts
src/utils/statement.parser.ts

refactor statement parser

---

src/utils/statement.parser.test.ts
src/utils/statement.parser.ts

parser can parse 2^n

---

src/pages/Login.tsx

Fix a typo in Login.tsx

---

src/components/JudgeStatusList.tsx
src/pages/Help.tsx

Fixes https://github.com/yosupo06/library-checker-problems/issues/848.
https://judge.yosupo.jp/help に ICE の項目を追加します。ついでに typo とかも直しています。

Help に ICE の項目を追記

---

src/pages/ProblemInfo.tsx

Fix typos in src/pages/ProblemInfo.tsx

---

src/components/MainContainer.tsx

set title tag
